[package]
name = "cryo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.3.4", features = ["derive"] }
ethers = { version = "2.0.7", features = ["rustls", "ws", "ipc"] }
eyre = "0.6.8"
futures = "0.3.28"
hex = "0.4.3"
polars = { version = "0.30.0", features = ["parquet"] }
ring = "0.16.20"
tokio = { version = "1.28.2", features = ["macros", "rt-multi-thread"] }

[profile.dev]
incremental = true
debug = 1
codegen-units = 32

