[package]
name = "cryo_freeze"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anstyle = "1.0.1"
async-trait = "0.1.68"
chrono = "0.4.26"
clap = { version = "4.3.4", features = ["derive", "color", "unstable-styles"] }
color-print = "0.3.4"
colored = "2.0.0"
ethers = { version = "2.0.7", features = ["rustls", "ws", "ipc"] }
eyre = "0.6.8"
futures = "0.3.28"
governor = "0.5.1"
hex = "0.4.3"
indexmap = "2.0.0"
indicatif = "0.17.5"
nonzero_ext = "0.3.0"
polars = { version = "0.30.0", features = ["parquet", "string_encoding", "polars-lazy", "lazy", "binary_encoding", "json", "dtype-struct"] }
prefix-hex = "0.7.0"
rayon = "1.7.0"
ring = "0.16.20"
thiserror = "1.0.40"
thousands = "0.2.0"
tokio = { version = "1.28.2", features = ["macros", "rt-multi-thread"] }

