[package]
name = "cryo_freeze"
version = "0.1.0"
edition = "2021"
description = "cryo is the easiest way to extract blockchain data to parquet, csv, or json"
repository = "https://github.com/paradigmxyz/cryo"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.68"
ethers = { version = "2.0.7", features = ["rustls", "ws", "ipc"] }
futures = "0.3.28"
governor = "0.5.1"
indexmap = "2.0.0"
indicatif = "0.17.5"
polars = { version = "0.30.0", features = ["parquet", "string_encoding", "polars-lazy", "lazy", "binary_encoding", "json", "dtype-struct"] }
prefix-hex = "0.7.0"
thiserror = "1.0.40"
tokio = { version = "1.28.2", features = ["macros", "rt-multi-thread", "sync"] }

